services:
  asset_server:
    build:
      context: ./nginx
      args:
        - DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
        - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
    ports:
      - "${DASHBOARD_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./app:/var/www/virtual_exhibition_webgl:ro,z
      - ./assets:/var/www/virtual_exhibition_assets:ro,z
      - ./admin:/var/www/virtual_exhibition_admin:ro,z
    depends_on:
      - api
  api:
    build: ./backend
    volumes:
      - ./assets:/app/assets:z
      - ./db:/app/db:z
      - ./backend:/app:z